### ISSUE TITLE
ImportError: No module named scapy.all

### ISSUE THREAD

**Issue by KittenYang** [tengzhangchao/WebSniff#1]
报错 ImportError: No module named scapy.all ，请问是什么原因?

**Comment by tengzhangchao** [comment]
scapy在linux下用比较好，不知道你是在linux下还是windows

**Comment by KittenYang** [comment]
@tengzhangchao  Linux(Mac OS 10.12)

**Comment by tengzhangchao** [comment]
当时也没有很好的测试过，待我完善一下。当时测试可以抓到本地htttp账号密码，局域网内的不一定可以。
